### ISSUE TITLE
halBranchMutations return coordinates

### ISSUE THREAD

**Issue by Varshith-C** [glennhickey/hal#29]
Hello,
       I am trying to compute the insertions in the human genome with respect to sus_scrofa and I have a HAL File that has its parent as sus_scrofa. I am using the following command to get the Insertion coordinates.
halBranchMutations --maxGap 20 --refFile output.bed input.hal homo_sapiens
When I try to check if the Insertion coordinates I get, match with the ENSEMBL data present, I get a discrepancy.
BED File Data:
1       207585826       207585834       GI      sus_scrofa      homo_sapiens

The corresponding ENSEMBL response is:

Alignment: Pig (sus scrofa) blastz 
Location:  1:207585826-207585834

Human ›	chromosome:GRCh37:1:207585826:207585834:1
Pig ›	chromosome:Sscrofa10.2:9:74418130:74418138:1
Human  AAAACTCCC
Pig    ACAATTTCC

Though the BED File says that there should be an insertion at that position, I don't find any Insertions. Am I doing something wrong? Are the way the coordinates being read different? Help me out.

Regards,
Varshith

**Comment by glennhickey** [comment]
Are your HAL and ENSEMBL alignments identical?  Otherwise there's no
guarantee that the gaps will line up.  If one was converted from the other
(via maf2hal), perhaps some information was lost (maf2hal does not handle
root paralogies for example).

As a sanity check, you can also run hal2maf on your query region and
inspect the output by eye to get a better idea what this block looks like
in the HAL file.

**Comment by Varshith-C** [comment]
Yeah Glenn I will try doing that to cross check how HAL Tools handle MAF files.
