### ISSUE TITLE
snake support

### ISSUE THREAD

**Issue by epaule** [glennhickey/hal#30]
according to: http://genome.ucsc.edu/goldenpath/help/trackDb/trackDbDoc.html#snake snake support is not for hubs making the makeAssemblyHub a bit less useful.

Is that still the case?

**Comment by joelarmstrong** [comment]
That's pretty outdated, the hal2assemblyHub script should produce assembly hubs with snake tracks by default.

**Comment by epaule** [comment]
In that case, do you know how to best debug snake tracks not rendering from HAL files?
I got an 29-way HAL from progressive cactus and calculated the lod zooming HALs, all served from an FTP and a HTTP server.

looks like that (as in: shows no error):
![screenshot from 2015-03-16 18 30 13](https://cloud.githubusercontent.com/assets/20523/6673395/8df51398-cc0a-11e4-85ff-0d2dafe6f667.png)

from http://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/mh6/myHub/genomes.txt
same at ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/mh6/myHub/genomes.txt

probably should lob it at the UCSC genome support forum instead of messing up github

**Comment by joelarmstrong** [comment]
There are 2 different issues:

- The lod.txt file you're using (http://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/mh6/myHub/lod.txt) refers to files in an lod/ subdirectory that is missing from the hub. This means that when zoomed out to a window size more than ~3kb, the snakes try accessing the lower-resolution hal files, which are missing from the hub.
- (more importantly) The elegans chromosomes have different names in the browser vs. in the hal file. For example, chromosome III is called 'III' in the browser but 'CHROMOSOME_III' in the hal file. The reference genome has to have the exact same naming scheme in the hal file as it does in the browser. There are a couple possible solutions to this. One "easy" solution would be to regenerate the 2bit file to use the 'CHROMOSOME_'-prefixed naming scheme, although I see you already have a bunch of tracks generated for the other naming scheme. Alternatively, you could regenerate or modify the hal file to use the unprefixed naming scheme. You wouldn't have to waste a bunch of time redoing the whole alignment for this--I could help rewrite the hal farily easily, especially if you have the progressiveCactus working directory for this alignment lying around.

Sorry about the lack of debug output. The browser could get the HAL error messages and display them, but it doesn't quite yet.

**Comment by epaule** [comment]
Thanks, I forgot about the prefixes :-)

**Comment by epaule** [comment]
I used B.malayi as demo worm, as the sequence ids are the same as in the HAL file, but neither adding the lod directory nor replacing the bigDataUrl to point to the hal file directly makes them render.

**Comment by joelarmstrong** [comment]
This time it's the genome names that don't match the HAL file. The snake track code uses the name from the "genome" field in genomes.txt to query the HAL file, so that field has to match the HAL genome name. That field isn't displayed anywhere on the browser itself, I think, so hopefully it shouldn't cause any visible changes. See my modified genomes.txt at:

http://hgwdev.cse.ucsc.edu/~jcarmstr/wormbaseHubTest/genomes.txt

which seems to work, although I've only tested on brugia:

![hgt_hgwdev_6a61_9e3c20](https://cloud.githubusercontent.com/assets/4723163/6719018/201559f2-cd75-11e4-9964-24f07684b74b.png)
Not sure why C.elegans doesn't show any alignment, but that's due to the alignment itself and not the snake tracks, I think. Maybe 

A working (but slow!) session is at: http://hgwdev.cse.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=jcarmstr&hgS_otherUserSessionName=hub_1250_brugia

**Comment by epaule** [comment]
thanks :-)

... and I really like the bits of additional debug info on you browser
instance

**Comment by joelarmstrong** [comment]
Hope this all works now. We've put in a request to add debug info into the browser view that will hopefully make it easier for users to diagnose issues with missing hal files or incorrect sequence/genome names, rather than just leaving the snake tracks blank when there's an error.

**Comment by epaule** [comment]
thanks. I still am a bit unsure about the intricate details of the configuration options, but it works fine.
![screenshot from 2015-03-24 09 35 41](https://cloud.githubusercontent.com/assets/20523/6798891/64cae420-d209-11e4-8462-3991497b2564.png)
